#!/usr/bin/env node
/**
 * lofi-check.js — the wireframe skill's missing guard.
 *
 * WHY THIS EXISTS: every other surface in the kit has an automated check (test-routekey.js,
 * test-prompts.js, test-wizard-url.js, path-refs.js, hygiene.js). `skills/wireframe-on-snapshot/`
 * had none — its two pre-render checklists (13 items) were verified in prose by the same agent that
 * just did the work, with nothing reading the artifact. Three cold runs of the design-new prompt read
 * §7.7 ("each region the library cannot ground gets … one `.lofi-tag` chip starting with `ASSUMED:`"),
 * wrote the assumption log into `notes.md`, ticked the checklist box, and tagged the canvas zero times.
 * Rewriting the prose a fourth time is the intervention that already failed three times. So: read the
 * artifact instead.
 *
 * THE PIXEL/DOM SPLIT — the trap this tool is built around. `lofi-mode` is `filter: grayscale(1)` on
 * <html>, a PAINT-TIME effect. `getComputedStyle` returns the ORIGINAL brand values, unchanged, on a
 * fully compliant page — measured here on a real one: 135 saturated computed-style properties
 * (`rgb(40, 116, 240)` Flipkart blue among them) against a render with a maximum channel spread of 0.
 * This is the same trap that cost two rounds on the Figma exit and produced `lofi-bake.js`. So:
 *   · every STRUCTURAL assertion measures the DOM  (1, 2, 3, 4, 5 — plus 6 and 8)
 *   · assertion 7 alone measures PIXELS in the render, never computed styles
 * Get that backwards per assertion and the checker is confidently wrong in both directions: a
 * computed-style saturation check reports a perfect score on a fully brand-colored page, and a
 * DOM-blind structural check can't see a region at all.
 *
 * WHAT IT DOES NOT DO: it reports and recommends. It never edits the wireframe, never touches
 * `design-context/`, never writes any file. No network (every non-`file://` request is aborted), no
 * server, works on a bare `file://` path, and degrades to skips — not crashes — when there is no
 * `design-context/` beside the wireframe.
 *
 * Usage: node tools/lofi-check.js <wireframe.html> [--json] [--width 1440] [--quiet]
 *        exit 1 = a structural assertion failed · exit 0 = clean, or heuristic warnings only
 */
const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');

const args = process.argv.slice(2);
const files = args.filter(a => !a.startsWith('--'));
const flag = f => args.includes(f);
const getArg = (f, d) => { const i = args.indexOf(f); return i !== -1 ? args[i + 1] : d; };

if (!files[0]) {
  console.error('usage: node tools/lofi-check.js <wireframe.html> [--json] [--width 1440] [--quiet]');
  process.exit(2);
}
const FILE = path.resolve(files[0]);
if (!fs.existsSync(FILE)) { console.error(`lofi-check: no such file — ${FILE}`); process.exit(2); }
const VIEWPORT_W = parseInt(getArg('--width', '1440'), 10);   // §7.4: pin to the capture viewport

// ── Calibrated constants — every one of these came off the real corpus, none was picked ─────────────
// Nine rounds across six products (19 wireframe files), plus two constructed cases. See
// prds/wireframe-check-BUILD-REPORT.md for the full triage table.
//
// SAT_DELTA — a pixel counts as saturated when max(R,G,B) − min(R,G,B) crosses this. 24 sits well past
//   8-bit rounding and PNG/antialias noise. At Δ≥24 the 7 corpus files carrying lofi-mode read EXACTLY
//   0 saturated pixels, and all 12 files without it read 0.66 %–37.75 %. There is no overlap to split.
// SAT_MIN_PX / SAT_MIN_FRAC — the trip point, bracketed by two measurements:
//   · one colored element that genuinely escapes the filter (a top-layer `popover`, which `filter` on
//     <html> does not reach) paints 2 906 px. 1 500 px sits below that, so a single real leak still
//     reports even on a 7.7 M-pixel full-page render, where it would be only 0.038 %.
//   · 0.05 % is 13× below the least-colored non-compliant page in the corpus (0.66 %) and unboundedly
//     above the compliant floor (0 px, 7/7 files).
//   Reported with counts and locations, and only ever a WARNING — because that top-layer escape means
//   a compliant page CAN carry saturated pixels, so a hard failure here would be wrong.
const SAT_DELTA = 24;
const SAT_MIN_PX = 1500;
const SAT_MIN_FRAC = 0.0005;
// A `.lofi-tag` chip is 1–3 words (§5:91 — `NEW`, `NEW: TIMELINE`). Corpus maximum: 3.
const TAG_MAX_WORDS = 3;
// Ground truth under design-context/ (hard rule #1). Deliberately NOT the derived views —
// page.md / registry.json / INDEX.md / dashboard.html are regenerated by build-index.js, so a newer
// mtime on those is a rebuild, not an edit.
const GROUND_TRUTH = ['page.html', 'screenshot.png', 'content.md', 'meta.json', 'computed-tokens.json'];

// ── Locate the canon and the workspace ─────────────────────────────────────────────────────────────
// Assertion 1 reads the canonical style blocks OUT OF SKILL.md at runtime rather than carrying a third
// copy in this file. That is the whole point: a pasted copy here would be one more mirror to drift, and
// this assertion exists to catch exactly that class of drift.
const SKILL_MD = path.join(__dirname, '..', 'skills', 'wireframe-on-snapshot', 'SKILL.md');

function findWorkspace(from) {
  let dir = path.dirname(from);
  for (let i = 0; i < 12; i++) {
    if (fs.existsSync(path.join(dir, 'design-context', 'registry.json'))) return dir;
    const up = path.dirname(dir);
    if (up === dir) break;
    dir = up;
  }
  return null;
}
const WS = findWorkspace(FILE);
const ROUND_DIR = path.dirname(FILE);
const NOTES = path.join(ROUND_DIR, 'notes.md');
// §7 work lives at wireframes/new/<concept>/round-N/ — that placement is what makes §7.4's <title>
// rule mandatory here and merely advisory elsewhere.
const IS_NEW_PAGE = /(^|[\\/])wireframes[\\/]new[\\/]/.test(FILE);

const canonBlock = (md, id) => {
  const m = new RegExp(`<style id="${id}">[\\s\\S]*?<\\/style>`).exec(md);
  return m ? m[0] : null;
};
const cssSelectors = css => [...new Set((css.match(/(^|[},])\s*([.#][A-Za-z][\w-]*(?:\.[\w-]+)*(?:\s+[.#>][\w-]+)*)/g) || [])
  .map(s => s.replace(/^[},]\s*/, '').trim()))].sort();

// ── Report plumbing ────────────────────────────────────────────────────────────────────────────────
const R = { file: FILE, structural: [], heuristic: [], info: [], notChecked: [] };
const add = (bucket, n, status, headline, detail = []) =>
  bucket.push({ n, status, headline, detail: [].concat(detail).filter(Boolean) });
const S = (n, status, h, d) => add(R.structural, n, status, h, d);   // fail → exit 1
const H = (n, status, h, d) => add(R.heuristic, n, status, h, d);    // warn → exit 0

(async () => {
  // ── The DOM pass and the pixel pass share ONE page load ─────────────────────────────────────────
  const browser = await chromium.launch();
  let blocked = 0, pageErrors = [];
  const page = await browser.newPage({ viewport: { width: VIEWPORT_W, height: 900 } });
  // "no network" is a house rule, not an aspiration — enforce it rather than hoping the snapshot is
  // fully inlined. Blocking can only ever REMOVE color, and remote images are `contrast(0)` anyway,
  // so this cannot manufacture a passing saturation reading.
  await page.route('**', route => {
    const u = route.request().url();
    if (u.startsWith('file://') || u.startsWith('data:') || u.startsWith('about:')) return route.continue();
    blocked++; return route.abort();
  });
  page.on('pageerror', e => pageErrors.push(String(e.message).split('\n')[0].slice(0, 120)));

  try {
    await page.goto('file://' + FILE, { waitUntil: 'load', timeout: 60000 });
  } catch (e) {
    console.error(`lofi-check: could not load ${path.basename(FILE)} — ${e.message.split('\n')[0]}`);
    await browser.close(); process.exit(2);
  }
  await page.waitForTimeout(800);

  const dom = await page.evaluate((cfg) => {
    const q = s => [...document.querySelectorAll(s)];
    // The kit's own vocabulary — the parts the designer DREW, as opposed to the captured shell.
    const DRAWN_SEL = '.lofi-region, .lofi-wire, .lofi-box, .lofi-img, .lofi-line, .lofi-steps, .lofi-spine';
    const drawn = q(DRAWN_SEL);
    const inDrawn = el => drawn.some(d => d === el || d.contains(el));
    const styleBlock = id => { const el = document.getElementById(id); return el ? el.outerHTML : null; };

    // — assertion 2: one chip per region, 1–3 words each —
    const regions = q('.lofi-region');
    const perRegion = regions.map((r, i) => {
      // a nested region owns its own chips; don't charge them to the ancestor
      const own = [...r.querySelectorAll('.lofi-tag')].filter(t => t.closest('.lofi-region') === r);
      return { i, count: own.length, text: own.map(t => (t.textContent || '').replace(/\s+/g, ' ').trim()) };
    });
    const chips = q('.lofi-tag').map(t => (t.textContent || '').replace(/\s+/g, ' ').trim()).filter(Boolean);

    // — assertion 6: prose annotation anywhere in the canvas (NOT scoped to drawn regions: a leak can
    //   sit in hand-edited shell markup, and one in the corpus does) —
    const walk = document.createTreeWalker(document.body || document.documentElement, NodeFilter.SHOW_TEXT);
    const bracket = /\[[^\]\[]*?\s[^\]\[]*?\s[^\]\[]*?\]/;   // ≥3 whitespace-separated tokens inside
    const capsRun = s => {
      const words = s.split(/[^A-Za-z0-9'’·\-]+/).filter(Boolean);
      let best = 0, run = 0;
      for (const w of words) {
        const letters = w.replace(/[^A-Za-z]/g, '');
        if (letters.length >= 2 && w === w.toUpperCase() && /[A-Z]/.test(w)) { run++; best = Math.max(best, run); }
        else run = 0;
      }
      return best;
    };
    const prose = [];
    let node;
    while ((node = walk.nextNode())) {
      const t = (node.textContent || '').replace(/\s+/g, ' ').trim();
      if (t.length < 2) continue;
      const el = node.parentElement;
      if (!el || el.closest('.lofi-tag') || el.closest('style, script, noscript, title')) continue;
      const cs = getComputedStyle(el);
      if (cs.display === 'none' || cs.visibility === 'hidden') continue;
      if (bracket.test(t)) prose.push({ kind: 'bracketed', text: t.slice(0, 90), drawn: inDrawn(el) });
      else if (capsRun(t) > 3) prose.push({ kind: `caps-run(${capsRun(t)})`, text: t.slice(0, 90), drawn: inDrawn(el) });
    }

    // — assertion 8: clipping and collisions, SCOPED to what the designer drew. The captured shell's
    //   own clipping is the product's, not the wireframe author's — scoping is what takes this
    //   heuristic from 230 hits on one page to 5 real ones. —
    const hasOwnText = el => [...el.childNodes].some(k => k.nodeType === 3 && k.textContent.trim().length > 1);
    const clipped = [];
    for (const el of q('*')) {
      if (!inDrawn(el) || !hasOwnText(el)) continue;
      const cs = getComputedStyle(el);
      if (cs.display === 'none' || cs.visibility === 'hidden' || !el.clientWidth || !el.clientHeight) continue;
      const hides = cs.overflow === 'hidden' || cs.overflowX === 'hidden' || cs.overflowY === 'hidden';
      if (!hides) continue;
      if (el.scrollWidth > el.clientWidth + 1 || el.scrollHeight > el.clientHeight + 1) {
        const r = el.getBoundingClientRect();
        clipped.push({
          sel: el.tagName.toLowerCase() + (el.classList[0] ? '.' + el.classList[0] : ''),
          text: (el.textContent || '').replace(/\s+/g, ' ').trim().slice(0, 44),
          box: `${el.scrollWidth}×${el.scrollHeight} in ${el.clientWidth}×${el.clientHeight}`,
          at: `${Math.round(r.x)},${Math.round(r.y + window.scrollY)}`,
        });
      }
    }
    const tagEls = q('.lofi-tag');
    const boxes = tagEls.map(t => t.getBoundingClientRect());
    const collisions = [];
    for (let i = 0; i < boxes.length; i++) for (let j = i + 1; j < boxes.length; j++) {
      const a = boxes[i], b = boxes[j];
      if (!a.width || !b.width) continue;
      if (a.left < b.right && b.left < a.right && a.top < b.bottom && b.top < a.bottom)
        collisions.push(`"${chips[i]}" ⇄ "${chips[j]}"`);
    }
    const docW = document.documentElement.scrollWidth;
    const spill = [];
    for (const el of drawn) {
      const cs = getComputedStyle(el);
      if (cs.display === 'none') continue;
      const r = el.getBoundingClientRect();
      if (r.width > 0 && (r.right > docW + 2 || r.left < -2))
        spill.push(`${el.tagName.toLowerCase()}.${el.classList[0] || ''} at ${Math.round(r.left)}…${Math.round(r.right)} vs doc ${docW}`);
    }

    // — landmine 1's evidence, collected so the report can SHOW the split rather than assert it —
    let satComputed = 0; const satComputedEg = [];
    for (const el of q('*')) {
      const cs = getComputedStyle(el);
      for (const prop of ['color', 'backgroundColor', 'borderTopColor']) {
        const m = /rgba?\((\d+),\s*(\d+),\s*(\d+)/.exec(cs[prop] || '');
        if (!m) continue;
        const [r, g, b] = [+m[1], +m[2], +m[3]];
        if (Math.max(r, g, b) - Math.min(r, g, b) >= cfg.satDelta) {
          satComputed++;
          if (satComputedEg.length < 3) satComputedEg.push(`${el.tagName.toLowerCase()} ${prop}=${cs[prop]}`);
        }
      }
    }

    return {
      title: document.title || '',
      mode: styleBlock('lofi-mode'), kit: styleBlock('lofi-kit'),
      rootFilter: getComputedStyle(document.documentElement).filter,
      regions: regions.length, perRegion, chips, drawnCount: drawn.length,
      prose, clipped, collisions, spill,
      satComputed, satComputedEg,
    };
  }, { satDelta: SAT_DELTA });

  const shot = await page.screenshot({ fullPage: true });
  await page.close();

  // ── The pixel pass. Decoded via canvas in a blank page so the tool needs no PNG dependency. ──────
  const pixPage = await browser.newPage();
  await pixPage.goto('about:blank');
  const px = await pixPage.evaluate(async ({ b64, delta }) => {
    const img = new Image();
    await new Promise((res, rej) => { img.onload = res; img.onerror = rej; img.src = 'data:image/png;base64,' + b64; });
    const c = document.createElement('canvas');
    c.width = img.naturalWidth; c.height = img.naturalHeight;
    const cx = c.getContext('2d', { willReadFrequently: true });
    cx.drawImage(img, 0, 0);
    const d = cx.getImageData(0, 0, c.width, c.height).data;
    let total = 0, sat = 0, max = 0;
    // cluster saturated pixels into coarse buckets so the report can name WHERE, not just how many
    const cells = new Map();
    const CELL = 64;
    for (let i = 0; i < d.length; i += 4) {
      if (d[i + 3] < 8) continue;
      total++;
      const dl = Math.max(d[i], d[i + 1], d[i + 2]) - Math.min(d[i], d[i + 1], d[i + 2]);
      if (dl > max) max = dl;
      if (dl < delta) continue;
      sat++;
      const p = i / 4, x = p % c.width, y = (p - x) / c.width;
      const k = `${Math.floor(x / CELL) * CELL},${Math.floor(y / CELL) * CELL}`;
      const cur = cells.get(k);
      if (cur) cur.n++; else cells.set(k, { n: 1, rgb: `rgb(${d[i]},${d[i + 1]},${d[i + 2]})` });
    }
    const top = [...cells.entries()].sort((a, b) => b[1].n - a[1].n).slice(0, 5)
      .map(([k, v]) => `${v.n}px near ${k} e.g. ${v.rgb}`);
    return { w: c.width, h: c.height, total, sat, max, top };
  }, { b64: shot.toString('base64'), delta: SAT_DELTA });
  await pixPage.close();
  await browser.close();

  const notes = fs.existsSync(NOTES) ? fs.readFileSync(NOTES, 'utf8') : null;

  // ══ ASSERTION 1 — the canonical blocks, byte-verbatim, read out of SKILL.md ═══════════════════════
  if (!fs.existsSync(SKILL_MD)) {
    S(1, 'skip', `no SKILL.md beside this tool — cannot verify the blocks without the canon`,
      `looked for ${path.relative(process.cwd(), SKILL_MD)}`);
  } else {
    const md = fs.readFileSync(SKILL_MD, 'utf8');
    const detail = [];
    let bad = 0, missing = 0;
    for (const id of ['lofi-mode', 'lofi-kit']) {
      const canon = canonBlock(md, id);
      const got = dom[id === 'lofi-mode' ? 'mode' : 'kit'];
      if (!canon) { detail.push(`SKILL.md carries no <style id="${id}"> — the canon itself is missing`); bad++; continue; }
      if (!got) { detail.push(`<style id="${id}"> absent from the wireframe`); missing++; continue; }
      if (got === canon) continue;
      bad++;
      const lost = cssSelectors(canon).filter(s => !cssSelectors(got).includes(s));
      const extra = cssSelectors(got).filter(s => !cssSelectors(canon).includes(s));
      const wsOnly = got.replace(/\s+/g, ' ').trim() === canon.replace(/\s+/g, ' ').trim();
      detail.push(`<style id="${id}"> differs from SKILL.md (${got.length} vs ${canon.length} bytes)`
        + (wsOnly ? ' — whitespace only' : '')
        + (lost.length ? ` · missing: ${lost.join(', ')}` : '')
        + (extra.length ? ` · extra: ${extra.join(', ')}` : ''));
      // Distinguish STALE from DRIFTED. If the wireframe's block is a strict subset of canon, the kit
      // gained selectors after this artifact was made — re-inject and move on. If it carries selectors
      // canon does not, someone hand-tuned the block, which is a different conversation.
      if (lost.length && !extra.length && !wsOnly)
        detail.push(`  ↳ strict subset of canon — this artifact predates a kit addition; re-inject the block from SKILL.md`);
      else if (extra.length)
        detail.push(`  ↳ carries selectors canon does not — the block was hand-tuned, not just stale`);
    }
    if (missing || bad) S(1, 'fail', `lofi-mode / lofi-kit not byte-verbatim against SKILL.md`, detail);
    else S(1, 'pass', `lofi-mode + lofi-kit present and byte-verbatim against SKILL.md`,
      `root filter is "${dom.rootFilter}"`);
  }

  // ══ ASSERTION 2 — exactly one chip per region, 1–3 words each ═════════════════════════════════════
  {
    const wrong = dom.perRegion.filter(r => r.count !== 1);
    const longChips = dom.chips.filter(c => c.split(/\s+/).filter(Boolean).length > TAG_MAX_WORDS);
    const detail = [
      ...wrong.map(r => `region #${r.i + 1} carries ${r.count} .lofi-tag chips${r.text.length ? ` (${r.text.map(t => `"${t}"`).join(', ')})` : ''}`),
      ...longChips.map(c => `chip "${c}" is ${c.split(/\s+/).filter(Boolean).length} words (max ${TAG_MAX_WORDS})`),
    ];
    if (!dom.regions && !dom.chips.length)
      S(2, 'pass', 'no .lofi-region on the canvas — nothing to pair (see 1: is this page in lofi mode?)');
    else if (detail.length) S(2, 'fail', `${dom.regions} .lofi-region · ${dom.chips.length} .lofi-tag — pairing is wrong`, detail);
    else S(2, 'pass', `${dom.regions} .lofi-region, each with exactly one .lofi-tag; all ${dom.chips.length} chips ≤ ${TAG_MAX_WORDS} words`,
      dom.chips.length ? dom.chips.map(c => `"${c}"`).join(' · ') : null);
  }

  // ══ ASSERTION 3 — THE GAP THIS TOOL EXISTS FOR: notes.md log ⇄ ASSUMED: chips on the canvas ═══════
  // Cross-file, both directions. An assumption log with an untagged canvas is the defect three cold
  // A.8 runs produced; an ASSUMED: chip with no log is an assumption nobody ever explained.
  {
    const chipAssumed = dom.chips.filter(c => /^ASSUMED\b/i.test(c));
    const hasLog = notes != null && (
      /^#{1,6}.*library could not tell me/im.test(notes) ||   // §7.7's own heading
      /\bASSUMED:/.test(notes) ||
      /^#{1,6}.*\bassumption/im.test(notes)
    );
    if (!hasLog && !chipAssumed.length) {
      S(3, 'pass', 'no assumption log in notes.md and no ASSUMED: chip — consistent',
        notes == null ? 'no notes.md beside this file' : null);
    } else if (hasLog && !chipAssumed.length) {
      S(3, 'fail', 'notes.md logs assumptions but the canvas carries no ASSUMED: chip',
        ['§7.7: each ungrounded region gets `class="lofi-region"` + one `.lofi-tag` starting with `ASSUMED:`',
         'the chip IS the in-canvas annotation — a notes.md entry does not substitute for it',
         `notes.md: ${path.relative(process.cwd(), NOTES)}`]);
    } else if (!hasLog && chipAssumed.length) {
      S(3, 'fail', `${chipAssumed.length} ASSUMED: chip(s) on the canvas with no assumption log in notes.md`,
        [chipAssumed.map(c => `"${c}"`).join(' · '),
         notes == null ? 'there is no notes.md beside this file' : 'notes.md has no "What the library could not tell me" section',
         '§7.7: the explanation goes in notes.md, one line per assumption']);
    } else {
      S(3, 'pass', `notes.md assumption log ⇄ ${chipAssumed.length} ASSUMED: chip(s) on the canvas`,
        chipAssumed.map(c => `"${c}"`).join(' · '));
    }
  }

  // ══ ASSERTION 4 — <title> must not be a captured page's title (§7.4) ═════════════════════════════
  if (!WS) {
    S(4, 'skip', 'no design-context/ above this file — cannot compare <title> against captured pages');
  } else {
    let reg = null, regErr = null;
    try { reg = JSON.parse(fs.readFileSync(path.join(WS, 'design-context', 'registry.json'), 'utf8')); }
    catch (e) { reg = null; regErr = e.message.split('\n')[0]; }
    if (!reg || !reg.pages) {
      S(4, 'skip', 'design-context/registry.json unreadable or carries no pages — <title> not compared', regErr);
    } else {
      const t = (dom.title || '').trim();
      const hits = Object.entries(reg.pages)
        .filter(([, p]) => p && typeof p.title === 'string' && p.title.trim() && p.title.trim() === t)
        .map(([slug]) => slug);
      if (!t) {
        S(4, IS_NEW_PAGE ? 'fail' : 'warn', 'the wireframe has no <title>',
          '§7.4: the Figma converter names the pasted frame from document.title — set it to `<This page> · <product>`');
      } else if (hits.length) {
        S(4, IS_NEW_PAGE ? 'fail' : 'info',
          `<title> is byte-identical to captured page ${hits.map(h => `"${h}"`).join(', ')}`,
          [`"${t}"`,
           '§7.4: leave it alone and this lands in Figma indistinguishable from the captured original',
           IS_NEW_PAGE ? 'structural here: this file is under wireframes/new/, which §7.4 governs'
                       : 'reported, not failed: §7.4 states this rule for new-page work; a same-page round inheriting its own title is expected']);
      } else {
        S(4, 'pass', `<title> "${t}" collides with no captured page (${Object.keys(reg.pages).length} compared)`);
      }
    }
  }

  // ══ ASSERTION 5 — the swap test is present in notes.md (§5:93) ═══════════════════════════════════
  // The DECIDABLE core is "a round with ≥2 approaches carries a swap test at all". Counting one line
  // PER PAIR is not: measured on the corpus, a compliant 3-approach round writes the word "swap" once
  // and then three `01 vs 03`-style bullets, while a compliant 2-approach round writes one sentence
  // with no pair label at all. Either per-pair counting rule fails one of those. So: fail on absence,
  // and REPORT pair-marker coverage as detail for the human — see the not-checked list.
  {
    const approaches = fs.readdirSync(ROUND_DIR)
      .filter(f => /^\d+[-_].*\.html?$/i.test(f) && !/\.baked\./i.test(f)).sort();
    const pairs = approaches.length >= 2 ? (approaches.length * (approaches.length - 1)) / 2 : 0;
    const hasSwapLanguage = notes != null && /\bswap(?:ped|ping|s)?\b/i.test(notes);
    const markers = new Set();
    if (notes != null) {
      const re = /\b(\d{1,2})\s*(?:vs\.?|versus)\s*(\d{1,2})\b/gi;
      let m; while ((m = re.exec(notes))) markers.add([+m[1], +m[2]].sort((a, b) => a - b).join('v'));
    }
    const coverage = `${markers.size}/${pairs} pair${pairs === 1 ? '' : 's'} named explicitly (e.g. "01 vs 02")`;
    if (!pairs) {
      S(5, 'pass', `${approaches.length} approach file(s) in this round — no pair to swap-test`);
    } else if (notes == null) {
      S(5, 'fail', `${approaches.length} approaches (${pairs} pair${pairs > 1 ? 's' : ''}) and no notes.md at all`,
        '§5:93 — one swap-test line per pair, written in notes.md before presenting');
    } else if (!hasSwapLanguage && !markers.size) {
      S(5, 'fail', `no swap test in notes.md for ${approaches.length} approaches (${pairs} pair${pairs > 1 ? 's' : ''})`,
        ['§5:93 — for each pair, one line: "A vs B — swapping their layouts breaks / doesn\'t break them, because …"',
         'if swapping does not break them they are the same model: merge, and replace one',
         `approaches: ${approaches.join(' · ')}`]);
    } else {
      S(5, 'pass', `swap test present in notes.md for ${pairs} approach pair${pairs > 1 ? 's' : ''}`,
        markers.size < pairs ? `${coverage} — read them yourself; per-pair coverage is not mechanically decidable` : coverage);
    }
  }

  // ══ ASSERTION 6 — prose annotation in the canvas (§5:91) — heuristic ═════════════════════════════
  if (!dom.prose.length) H(6, 'pass', 'no prose annotation found in the canvas');
  else H(6, 'warn', `${dom.prose.length} possible prose annotation(s) in the canvas`,
    [...dom.prose.slice(0, 6).map(p => `${p.kind}${p.drawn ? ' (in a drawn region)' : ''}: "${p.text}"`),
     dom.prose.length > 6 ? `… and ${dom.prose.length - 6} more` : null,
     '§5:91 — the chip is the only annotation allowed in the canvas; editorial remarks go in notes.md']);

  // ══ ASSERTION 7 — saturated pixels IN THE RENDER (never computed styles) — heuristic ═════════════
  {
    const frac = px.total ? px.sat / px.total : 0;
    const over = px.sat >= SAT_MIN_PX || frac >= SAT_MIN_FRAC;
    const label = `${px.sat.toLocaleString()} saturated px (${(frac * 100).toFixed(4)} % of ${px.total.toLocaleString()} opaque, Δ≥${SAT_DELTA}, max Δ ${px.max})`;
    if (over) H(7, 'warn', `${label} — over the ${SAT_MIN_PX} px / ${(SAT_MIN_FRAC * 100).toFixed(2)} % trip point`,
      [...px.top, `render ${px.w}×${px.h} at viewport width ${VIEWPORT_W}`,
       'measured in the RENDER, not computed styles — lofi-mode is a paint-time filter',
       'a compliant page may still carry a few (top-layer content escapes `filter` on <html>) — read the locations before acting']);
    else H(7, 'pass', label, `under the ${SAT_MIN_PX} px / ${(SAT_MIN_FRAC * 100).toFixed(2)} % trip point`);
  }

  // ══ ASSERTION 8 — clipping / collision in the render (the §107 check, partially mechanized) ══════
  {
    const detail = [
      ...dom.clipped.slice(0, 8).map(c => `clipped: ${c.sel} "${c.text}" — ${c.box} at (${c.at})`),
      dom.clipped.length > 8 ? `… and ${dom.clipped.length - 8} more clipped` : null,
      ...dom.collisions.slice(0, 4).map(c => `chips overlap: ${c}`),
      ...dom.spill.slice(0, 4).map(s => `spills past the document width: ${s}`),
    ].filter(Boolean);
    const n = dom.clipped.length + dom.collisions.length + dom.spill.length;
    if (!dom.drawnCount) H(8, 'skip', 'no drawn regions to check for clipping (nothing carries the kit classes)');
    else if (!n) H(8, 'pass', `no clipping, chip overlap, or spill inside the ${dom.drawnCount} drawn region(s)`);
    else H(8, 'warn', `${n} render problem(s) inside the drawn regions`,
      [...detail, '§107 still stands — open the PNG and look; this supplements your eyes, it does not replace them']);
  }

  // ══ ASSERTION 9 — library-untouched tripwire (hard rule #1 has had no detector) — info ═══════════
  if (!WS) {
    R.info.push({ n: 9, status: 'skip', headline: 'no design-context/ above this file — library tripwire not run', detail: [] });
  } else {
    const wfTime = fs.statSync(FILE).mtimeMs;
    const newer = [];
    const walkDir = (d, depth) => {
      if (depth > 4 || newer.length > 40) return;
      let ents = [];
      try { ents = fs.readdirSync(d, { withFileTypes: true }); } catch (e) { return; }
      for (const e of ents) {
        const p = path.join(d, e.name);
        if (e.isDirectory()) walkDir(p, depth + 1);
        else if (GROUND_TRUTH.includes(e.name)) {
          try { const m = fs.statSync(p).mtimeMs; if (m > wfTime) newer.push({ p: path.relative(WS, p), m }); } catch (e2) { /* unreadable */ }
        }
      }
    };
    walkDir(path.join(WS, 'design-context'), 0);
    if (!newer.length) {
      R.info.push({ n: 9, status: 'pass', headline: `library untouched since this wireframe — no ground-truth file is newer`, detail: [] });
    } else {
      newer.sort((a, b) => b.m - a.m);
      // Group by day: one shared date across many files reads as a re-capture, a lone outlier does not.
      const byDay = new Map();
      for (const x of newer) {
        const d = new Date(x.m).toISOString().slice(0, 10);
        byDay.set(d, (byDay.get(d) || 0) + 1);
      }
      const days = [...byDay.entries()].sort((a, b) => (a[0] < b[0] ? 1 : -1));
      R.info.push({ n: 9, status: 'info', headline: `${newer.length} ground-truth file(s) under design-context/ are newer than this wireframe`,
        detail: [
          ...days.map(([d, n]) => `${n} file(s) dated ${d}`),
          `newest: ${newer[0].p} — ${new Date(newer[0].m).toISOString().slice(0, 16).replace('T', ' ')}`,
          days.length === 1
            ? 'all on one date — consistent with a re-capture, which is innocent. Reported, not accused.'
            : 'spread across dates — worth a look; hard rule #1 says only a capture writes these. Reported, not accused.',
        ] });
    }
  }

  // ── Named non-coverage. A checker that pretends to cover these is worse than one that admits it. ──
  R.notChecked = [
    'invented identifiers (§7.6) — order IDs, tracking numbers, courier names: not mechanically decidable',
    'the density floor (§5:94) — "density ≥ the captured page" needs a human read of both',
    'approaches differing in MODEL, not decoration (§5:93) — assertion 5 finds the swap test, it cannot judge it',
    'clone-and-edit provenance (§5:90) — whether a region was cloned from a captured element or fabricated',
    'per-PAIR swap-test coverage (§5:93) — assertion 5 fails on absence only; whether every pair got its own line is a read, not a count',
    'per-chip ↔ per-line matching for assertion 3 — the categorical check is decidable, subject matching is not',
  ];

  // ── Emit ─────────────────────────────────────────────────────────────────────────────────────────
  const failed = R.structural.filter(a => a.status === 'fail');
  const warned = R.heuristic.filter(a => a.status === 'warn');

  if (flag('--json')) {
    console.log(JSON.stringify({
      file: FILE, workspace: WS, isNewPage: IS_NEW_PAGE,
      structural: R.structural, heuristic: R.heuristic, info: R.info, notChecked: R.notChecked,
      evidence: { satComputed: dom.satComputed, satComputedEg: dom.satComputedEg, satPixels: px.sat,
        maxDelta: px.max, render: `${px.w}x${px.h}`, blockedRequests: blocked, pageErrors },
      thresholds: { SAT_DELTA, SAT_MIN_PX, SAT_MIN_FRAC, TAG_MAX_WORDS },
      exit: failed.length ? 1 : 0,
    }, null, 2));
  } else {
    const GLYPH = { pass: '✓', fail: '✗', warn: '⚠', skip: '·', info: '·' };
    const line = a => {
      console.log(`  ${GLYPH[a.status]} ${a.n} · ${a.headline}`);
      for (const d of a.detail) console.log(`        ${d}`);
    };
    console.log(`\nlofi-check · ${path.relative(process.cwd(), FILE)}`);
    console.log(`  workspace  ${WS ? path.relative(path.dirname(WS), WS) + ' (design-context/ present)' : 'standalone — no design-context/ found'}`);
    console.log(`  canon      ${fs.existsSync(SKILL_MD) ? path.relative(path.join(__dirname, '..'), SKILL_MD) : 'NOT FOUND'}`);
    console.log(`  render     ${px.w}×${px.h}, ${blocked} network request(s) blocked${pageErrors.length ? `, ${pageErrors.length} page error(s)` : ''}`);
    if (!flag('--quiet')) {
      // The split, stated on every run — this is the landmine, so make it impossible to miss.
      const verdict = dom.satComputed && !px.sat
        ? 'the filter is doing its job at paint time; a computed-style check here would report full brand color and be confidently wrong'
        : !dom.satComputed && px.sat
          ? 'color is in the paint but not in these three properties (images, gradients, SVG) — a DOM-only check would miss it'
          : px.sat ? 'both nonzero — color reaches the paint' : 'both zero';
      console.log(`  pixel/DOM  ${dom.satComputed} saturated computed-style properties vs ${px.sat} saturated pixels — ${verdict}`);
    }
    console.log('\nSTRUCTURAL — a failure here exits 1');
    R.structural.forEach(line);
    console.log('\nHEURISTIC — warnings only, never fails the check');
    R.heuristic.forEach(line);
    console.log('\nINFO');
    R.info.forEach(line);
    console.log('\nNOT CHECKED — human judgment, by design');
    R.notChecked.forEach(s => console.log(`  · ${s}`));
    const skipped = R.structural.filter(a => a.status === 'skip').length;
    console.log(`\n${failed.length ? '❌' : '✅'}  ${R.structural.filter(a => a.status === 'pass').length} structural passed`
      + `${failed.length ? `, ${failed.length} FAILED` : ''}`
      + `${skipped ? `, ${skipped} skipped` : ''}`
      + ` · ${warned.length} warning${warned.length === 1 ? '' : 's'}\n`);
  }
  process.exit(failed.length ? 1 : 0);
})().catch(e => { console.error('lofi-check failed:', e.message); process.exit(2); });
